### ISSUE TITLE
Change use of Mycroft JSON config file to a skill-only YAML configuration file

### ISSUE THREAD

**Issue by LinusSkucas** [LinusS1/email-skill#14]
Using Config file with self.config in skills will end with the 19.08 release. Change so that it uses another file if users don't want to use home. The file will be ~/.mycroft/email-skill/email.yml. I will use yaml.

Before 19.08:
-----
- [x] Define `self.config`  in the skill.

In the Longer Run:
-----
- [x] Change code to use YAML file, over home settings, if existent.

- [ ] Keep backwards compatibility with Config file

> I might want to have the skill say if the user is using the old config file something like: `You are using the old version of configuring the skill on the device. Please go to [insert url here] to learn more.`

- [x] Update docs
  - [x] Change the config file to the yaml file
  - [ ] Create a "moving" page which user will land on when directed by the skill (see above)

- [x] Promote change.

**Comment by LinusSkucas** [comment]
Found that I could get around this with the Mycroft Config. just define `self.config`  My self. However, I should just switch it to yaml because its is nicer.

I'm going to keep the `bug` label on this issue until I define `self.config` in the skill.

Sample code which could do this:
```python
from mycroft.configuration.config import DEFAULT_CONFIG, SYSTEM_CONFIG, USER_CONFIG
from mycroft.configuration import Configuration

self.config = Configuration.get([DEFAULT_CONFIG,
                                    SYSTEM_CONFIG,
                                    USER_CONFIG],
                                   cache=False)
```

**Comment by JonahEmbry** [comment]
So what exactly do I have to do to get this skill to work? I've been fighting with this for the last couple days, so any help would be appreciated.

**Comment by LinusSkucas** [comment]
right now, the local configuration isn't working due to some changes made in Mycroft core. This is on my todo list.

**Comment by LinusSkucas** [comment]
Hi @JonahEmbry The skill has been updated to fix this problem, and has been submitted to the market place for review. Once it is accepted, you should use the new docs to configure the skill. Alternatively, just using the home.mycroft.ai settings has been verified to work.
