### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PureTryOut** [LinusS1/email-skill#21]
Hey, this skill actually has releases! :smile: 

I'm wondering if you could make a new release, since it seems e77b6fc64009db1c5af5378036404504d00b58d9 is quite important to get it running with the latest Mycroft.

**Comment by LinusSkucas** [comment]
Hi there! I believe that commit is already available to mycroft devices, however I totally forgot to make a new release. 

I've made a new release:  v1.6.5. I'll push that to review, which will be quick then it will be available on Mycroft devices.

**Comment by PureTryOut** [comment]
Thanks! I forgot to give some context for this request, as I'm not actually installing skills the usual way.

I'm in the process of packaging Mycroft and it's skills for distribution packaging, in this case for Alpine Linux. The goal is to install the skills via the package manager rather than via the Mycroft marketplace. And for distribution packaging you need tagged releases :wink:

**Comment by LinusSkucas** [comment]
Sure thing, it sounds cool!
