### ISSUE TITLE
consider using https://github.com/JarbasAl/mail_monitor

### ISSUE THREAD

**Issue by JarbasAl** [LinusS1/email-skill#22]
I made a quick package to handle monitoring email

consider using https://github.com/JarbasAl/mail_monitor

see https://community.mycroft.ai/t/testing-and-feedback-email-commands-skill/9417 for a different skill using it

also allows you to read the content of the email, first step to solve https://github.com/LinusS1/email-skill/issues/12

supports a sender whitelist, which allows solving https://github.com/LinusS1/email-skill/issues/4

**Comment by LinusSkucas** [comment]
Woah, thanks! I’ll look into it. I need to get back into doing mycroft stuff.

**Comment by JarbasAl** [comment]
you can also instantiate more than one mail_monitor if needed

either for different emails, or to handle https://github.com/LinusS1/email-skill/issues/17

and yes, you should get back into mycroft :)
