### ISSUE TITLE
[Feature suggestion] Get noticed of new emails

### ISSUE THREAD

**Issue by adocampo** [LinusS1/email-skill#4]
First of all, congratulations for this skill!

I was thinking it will be super useful to tell mycroft to notice me when I waiting for an concrete email from someone. I do not want -personally- to get noticed of each and every email I get, but if I'm waiting for someone's answer or perhaps some monitor alert of my job, tell Mycroft something like "let me know when I get an email from {sender}".

What do you think?

**Comment by LinusSkucas** [comment]
@adocampo thanks for the suggestion!
For the next update I’ll defiantly include this along with other things such as summarizing the message.
The only worry I have with this is if mycroft can understand the  spoken name. 
Thanks again for the Spanish translation 😀

**Comment by adocampo** [comment]
Thank you for including that feature! :smile: 
Well, I guess if mycroft uses natural language processing, it should be able to understand normal names, although perhaps it will have some troubles certain words like company names or nicknames. But hey, perhaps NLP is good enough!

Summarizing the email is a great feature as well!! :+1:

**Comment by JarbasAl** [comment]
i suggest using https://github.com/seatgeek/fuzzywuzzy

this allows to match persons better, use the confidence to disambiguate, and maybe ask the user if there are similar sounding users and confidence is low

**Comment by adocampo** [comment]
Closed? That means this feature request is being added?

**Comment by LinusSkucas** [comment]
It already is! "Hey Mycroft, tell me when I get email from ___"
